// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace ProductCatalog.Acceptance.Tests.Features.MobilePhones
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class DeleteMobilePhoneFeature : object, global::Xunit.IClassFixture<DeleteMobilePhoneFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/MobilePhones", "Delete mobile phone", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "DeleteMobilePhone.feature"
#line hidden
        
        public DeleteMobilePhoneFeature(DeleteMobilePhoneFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/MobilePhones/DeleteMobilePhone.feature.ndjson", 4);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Delete mobile phone returns ok response")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Delete mobile phone")]
        [global::Xunit.TraitAttribute("Description", "Delete mobile phone returns ok response")]
        public async global::System.Threading.Tasks.Task DeleteMobilePhoneReturnsOkResponse()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Delete mobile phone returns ok response", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 3
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table5 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table5.AddRow(new string[] {
                            "Name",
                            "Test Mobile Phone"});
                table5.AddRow(new string[] {
                            "Brand",
                            "Brand"});
                table5.AddRow(new string[] {
                            "Description",
                            "Phone created by acceptance test"});
                table5.AddRow(new string[] {
                            "MainPhoto",
                            "main-photo.jpg"});
                table5.AddRow(new string[] {
                            "OtherPhotos",
                            "photo-1.jpg, photo-2.jpg"});
                table5.AddRow(new string[] {
                            "CPU",
                            "Octa-core"});
                table5.AddRow(new string[] {
                            "GPU",
                            "Adreno"});
                table5.AddRow(new string[] {
                            "Ram",
                            "8GB"});
                table5.AddRow(new string[] {
                            "Storage",
                            "256GB"});
                table5.AddRow(new string[] {
                            "DisplayType",
                            "OLED"});
                table5.AddRow(new string[] {
                            "RefreshRateHz",
                            "120"});
                table5.AddRow(new string[] {
                            "ScreenSizeInches",
                            "6.4"});
                table5.AddRow(new string[] {
                            "Width",
                            "72"});
                table5.AddRow(new string[] {
                            "Height",
                            "152"});
                table5.AddRow(new string[] {
                            "BatteryType",
                            "Li-Ion"});
                table5.AddRow(new string[] {
                            "BatteryCapacity",
                            "4500"});
                table5.AddRow(new string[] {
                            "Has5G",
                            "true"});
                table5.AddRow(new string[] {
                            "WiFi",
                            "true"});
                table5.AddRow(new string[] {
                            "NFC",
                            "true"});
                table5.AddRow(new string[] {
                            "Bluetooth",
                            "true"});
                table5.AddRow(new string[] {
                            "GPS",
                            "true"});
                table5.AddRow(new string[] {
                            "AGPS",
                            "true"});
                table5.AddRow(new string[] {
                            "Galileo",
                            "true"});
                table5.AddRow(new string[] {
                            "GLONASS",
                            "true"});
                table5.AddRow(new string[] {
                            "QZSS",
                            "true"});
                table5.AddRow(new string[] {
                            "Accelerometer",
                            "true"});
                table5.AddRow(new string[] {
                            "Gyroscope",
                            "true"});
                table5.AddRow(new string[] {
                            "Proximity",
                            "true"});
                table5.AddRow(new string[] {
                            "Compass",
                            "true"});
                table5.AddRow(new string[] {
                            "Barometer",
                            "true"});
                table5.AddRow(new string[] {
                            "Halla",
                            "false"});
                table5.AddRow(new string[] {
                            "AmbientLight",
                            "true"});
                table5.AddRow(new string[] {
                            "Camera",
                            "camera"});
                table5.AddRow(new string[] {
                            "FingerPrint",
                            "true"});
                table5.AddRow(new string[] {
                            "FaceId",
                            "true"});
                table5.AddRow(new string[] {
                            "PriceAmount",
                            "799.99"});
                table5.AddRow(new string[] {
                            "PriceCurrency",
                            "USD"});
                table5.AddRow(new string[] {
                            "Description2",
                            "desc2"});
                table5.AddRow(new string[] {
                            "Description3",
                            "desc3"});
#line 4
    await testRunner.GivenAsync("an existing mobile phone to delete", ((string)(null)), table5, "Given ");
#line hidden
#line 45
    await testRunner.WhenAsync("I submit the delete mobile phone request", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table6 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table6.AddRow(new string[] {
                            "StatusCode",
                            "200"});
                table6.AddRow(new string[] {
                            "HasId",
                            "true"});
                table6.AddRow(new string[] {
                            "IsActive",
                            "false"});
                table6.AddRow(new string[] {
                            "Name",
                            "Test Mobile Phone"});
                table6.AddRow(new string[] {
                            "Brand",
                            "Brand"});
                table6.AddRow(new string[] {
                            "PriceAmount",
                            "799.99"});
                table6.AddRow(new string[] {
                            "PriceCurrency",
                            "USD"});
#line 46
    await testRunner.ThenAsync("the mobile phone is deleted successfully", ((string)(null)), table6, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Delete mobile phone fails for missing mobile phone")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Delete mobile phone")]
        [global::Xunit.TraitAttribute("Description", "Delete mobile phone fails for missing mobile phone")]
        public async global::System.Threading.Tasks.Task DeleteMobilePhoneFailsForMissingMobilePhone()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Delete mobile phone fails for missing mobile phone", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 56
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 57
    await testRunner.GivenAsync("a mobile phone id that does not exist", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 58
    await testRunner.WhenAsync("I submit the delete mobile phone request for missing mobile phone", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table7 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table7.AddRow(new string[] {
                            "StatusCode",
                            "400"});
                table7.AddRow(new string[] {
                            "Title",
                            "Validation failed"});
                table7.AddRow(new string[] {
                            "Detail",
                            "One or more validation errors occurred."});
                table7.AddRow(new string[] {
                            "ErrorMessage",
                            "Mobile phone cannot be null."});
                table7.AddRow(new string[] {
                            "ErrorEntity",
                            "MobilePhone"});
                table7.AddRow(new string[] {
                            "ErrorName",
                            "MobilePhonesIsNullValidationRule"});
#line 59
    await testRunner.ThenAsync("the mobile phone deletion fails with validation errors", ((string)(null)), table7, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await DeleteMobilePhoneFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await DeleteMobilePhoneFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
