// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace ProductCatalog.Acceptance.Tests.Features.MobilePhones
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class GetMobilePhonesByIdsNotFoundFeature : object, global::Xunit.IClassFixture<GetMobilePhonesByIdsNotFoundFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/MobilePhones", "Get mobile phones by ids not found", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "GetMobilePhonesByIdsNotFound.feature"
#line hidden
        
        public GetMobilePhonesByIdsNotFoundFeature(GetMobilePhonesByIdsNotFoundFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/MobilePhones/GetMobilePhonesByIdsNotFound.feature.ndjson", 3);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Get mobile phones by ids fails when one requested mobile phone does not exist")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Get mobile phones by ids not found")]
        [global::Xunit.TraitAttribute("Description", "Get mobile phones by ids fails when one requested mobile phone does not exist")]
        public async global::System.Threading.Tasks.Task GetMobilePhonesByIdsFailsWhenOneRequestedMobilePhoneDoesNotExist()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Get mobile phones by ids fails when one requested mobile phone does not exist", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 3
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table55 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table55.AddRow(new string[] {
                            "Name",
                            "Test Mobile Phone"});
                table55.AddRow(new string[] {
                            "Brand",
                            "Brand"});
                table55.AddRow(new string[] {
                            "Description",
                            "Phone created by acceptance test"});
                table55.AddRow(new string[] {
                            "MainPhoto",
                            "main-photo.jpg"});
                table55.AddRow(new string[] {
                            "OtherPhotos",
                            "photo-1.jpg, photo-2.jpg"});
                table55.AddRow(new string[] {
                            "CPU",
                            "Octa-core"});
                table55.AddRow(new string[] {
                            "GPU",
                            "Adreno"});
                table55.AddRow(new string[] {
                            "Ram",
                            "8GB"});
                table55.AddRow(new string[] {
                            "Storage",
                            "256GB"});
                table55.AddRow(new string[] {
                            "DisplayType",
                            "OLED"});
                table55.AddRow(new string[] {
                            "RefreshRateHz",
                            "120"});
                table55.AddRow(new string[] {
                            "ScreenSizeInches",
                            "6.4"});
                table55.AddRow(new string[] {
                            "Width",
                            "72"});
                table55.AddRow(new string[] {
                            "Height",
                            "152"});
                table55.AddRow(new string[] {
                            "BatteryType",
                            "Li-Ion"});
                table55.AddRow(new string[] {
                            "BatteryCapacity",
                            "4500"});
                table55.AddRow(new string[] {
                            "Has5G",
                            "true"});
                table55.AddRow(new string[] {
                            "WiFi",
                            "true"});
                table55.AddRow(new string[] {
                            "NFC",
                            "true"});
                table55.AddRow(new string[] {
                            "Bluetooth",
                            "true"});
                table55.AddRow(new string[] {
                            "GPS",
                            "true"});
                table55.AddRow(new string[] {
                            "AGPS",
                            "true"});
                table55.AddRow(new string[] {
                            "Galileo",
                            "true"});
                table55.AddRow(new string[] {
                            "GLONASS",
                            "true"});
                table55.AddRow(new string[] {
                            "QZSS",
                            "true"});
                table55.AddRow(new string[] {
                            "Accelerometer",
                            "true"});
                table55.AddRow(new string[] {
                            "Gyroscope",
                            "true"});
                table55.AddRow(new string[] {
                            "Proximity",
                            "true"});
                table55.AddRow(new string[] {
                            "Compass",
                            "true"});
                table55.AddRow(new string[] {
                            "Barometer",
                            "true"});
                table55.AddRow(new string[] {
                            "Halla",
                            "false"});
                table55.AddRow(new string[] {
                            "AmbientLight",
                            "true"});
                table55.AddRow(new string[] {
                            "Camera",
                            "camera"});
                table55.AddRow(new string[] {
                            "FingerPrint",
                            "true"});
                table55.AddRow(new string[] {
                            "FaceId",
                            "true"});
                table55.AddRow(new string[] {
                            "PriceAmount",
                            "799.99"});
                table55.AddRow(new string[] {
                            "PriceCurrency",
                            "USD"});
                table55.AddRow(new string[] {
                            "Description2",
                            "desc2"});
                table55.AddRow(new string[] {
                            "Description3",
                            "desc3"});
#line 4
    await testRunner.GivenAsync("an existing mobile phone and a missing mobile phone id", ((string)(null)), table55, "Given ");
#line hidden
                global::Reqnroll.Table table56 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table56.AddRow(new string[] {
                            "ExistingMobilePhoneId",
                            "{MobilePhoneId}"});
                table56.AddRow(new string[] {
                            "MissingMobilePhoneId",
                            "{MissingMobilePhoneId}"});
#line 45
    await testRunner.WhenAsync("I request the mobile phones by ids", ((string)(null)), table56, "When ");
#line hidden
                global::Reqnroll.Table table57 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table57.AddRow(new string[] {
                            "StatusCode",
                            "404"});
                table57.AddRow(new string[] {
                            "Title",
                            "Resource not found."});
                table57.AddRow(new string[] {
                            "Detail",
                            "Resource MobilePhoneDto identify by id {MissingMobilePhoneId} cannot be found in " +
                                "databese during action GetMobilePhoneByIdsQuery."});
                table57.AddRow(new string[] {
                            "Instance",
                            "/mobile-phones/by-ids"});
#line 49
    await testRunner.ThenAsync("the get mobile phones by ids response is not found", ((string)(null)), table57, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await GetMobilePhonesByIdsNotFoundFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await GetMobilePhonesByIdsNotFoundFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
