// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace ProductCatalog.Acceptance.Tests.Features.MobilePhones
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class GetMobilePhonesByIdsFeature : object, global::Xunit.IClassFixture<GetMobilePhonesByIdsFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/MobilePhones", "Get mobile phones by ids", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "GetMobilePhonesByIds.feature"
#line hidden
        
        public GetMobilePhonesByIdsFeature(GetMobilePhonesByIdsFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/MobilePhones/GetMobilePhonesByIds.feature.ndjson", 3);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Get mobile phones by ids returns the requested mobile phones")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Get mobile phones by ids")]
        [global::Xunit.TraitAttribute("Description", "Get mobile phones by ids returns the requested mobile phones")]
        public async global::System.Threading.Tasks.Task GetMobilePhonesByIdsReturnsTheRequestedMobilePhones()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Get mobile phones by ids returns the requested mobile phones", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 3
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table51 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table51.AddRow(new string[] {
                            "Name",
                            "First By Ids Phone"});
                table51.AddRow(new string[] {
                            "Brand",
                            "First Brand"});
                table51.AddRow(new string[] {
                            "Description",
                            "First phone requested by id"});
                table51.AddRow(new string[] {
                            "MainPhoto",
                            "first-main-photo.jpg"});
                table51.AddRow(new string[] {
                            "OtherPhotos",
                            "first-photo-1.jpg, first-photo-2.jpg"});
                table51.AddRow(new string[] {
                            "CPU",
                            "First Octa-core"});
                table51.AddRow(new string[] {
                            "GPU",
                            "First Adreno"});
                table51.AddRow(new string[] {
                            "Ram",
                            "8GB"});
                table51.AddRow(new string[] {
                            "Storage",
                            "256GB"});
                table51.AddRow(new string[] {
                            "DisplayType",
                            "First OLED"});
                table51.AddRow(new string[] {
                            "RefreshRateHz",
                            "120"});
                table51.AddRow(new string[] {
                            "ScreenSizeInches",
                            "6.4"});
                table51.AddRow(new string[] {
                            "Width",
                            "72"});
                table51.AddRow(new string[] {
                            "Height",
                            "152"});
                table51.AddRow(new string[] {
                            "BatteryType",
                            "Li-Ion"});
                table51.AddRow(new string[] {
                            "BatteryCapacity",
                            "4500"});
                table51.AddRow(new string[] {
                            "Has5G",
                            "true"});
                table51.AddRow(new string[] {
                            "WiFi",
                            "true"});
                table51.AddRow(new string[] {
                            "NFC",
                            "true"});
                table51.AddRow(new string[] {
                            "Bluetooth",
                            "true"});
                table51.AddRow(new string[] {
                            "GPS",
                            "true"});
                table51.AddRow(new string[] {
                            "AGPS",
                            "true"});
                table51.AddRow(new string[] {
                            "Galileo",
                            "true"});
                table51.AddRow(new string[] {
                            "GLONASS",
                            "true"});
                table51.AddRow(new string[] {
                            "QZSS",
                            "true"});
                table51.AddRow(new string[] {
                            "Accelerometer",
                            "true"});
                table51.AddRow(new string[] {
                            "Gyroscope",
                            "true"});
                table51.AddRow(new string[] {
                            "Proximity",
                            "true"});
                table51.AddRow(new string[] {
                            "Compass",
                            "true"});
                table51.AddRow(new string[] {
                            "Barometer",
                            "true"});
                table51.AddRow(new string[] {
                            "Halla",
                            "false"});
                table51.AddRow(new string[] {
                            "AmbientLight",
                            "true"});
                table51.AddRow(new string[] {
                            "Camera",
                            "first camera"});
                table51.AddRow(new string[] {
                            "FingerPrint",
                            "true"});
                table51.AddRow(new string[] {
                            "FaceId",
                            "true"});
                table51.AddRow(new string[] {
                            "PriceAmount",
                            "799.99"});
                table51.AddRow(new string[] {
                            "PriceCurrency",
                            "USD"});
                table51.AddRow(new string[] {
                            "Description2",
                            "first desc2"});
                table51.AddRow(new string[] {
                            "Description3",
                            "first desc3"});
#line 4
    await testRunner.GivenAsync("an existing mobile phone for the by ids request", ((string)(null)), table51, "Given ");
#line hidden
                global::Reqnroll.Table table52 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table52.AddRow(new string[] {
                            "Name",
                            "Second By Ids Phone"});
                table52.AddRow(new string[] {
                            "Brand",
                            "Second Brand"});
                table52.AddRow(new string[] {
                            "Description",
                            "Second phone requested by id"});
                table52.AddRow(new string[] {
                            "MainPhoto",
                            "second-main-photo.jpg"});
                table52.AddRow(new string[] {
                            "OtherPhotos",
                            "second-photo-1.jpg, second-photo-2.jpg"});
                table52.AddRow(new string[] {
                            "CPU",
                            "Second Octa-core"});
                table52.AddRow(new string[] {
                            "GPU",
                            "Second Adreno"});
                table52.AddRow(new string[] {
                            "Ram",
                            "12GB"});
                table52.AddRow(new string[] {
                            "Storage",
                            "512GB"});
                table52.AddRow(new string[] {
                            "DisplayType",
                            "Second AMOLED"});
                table52.AddRow(new string[] {
                            "RefreshRateHz",
                            "144"});
                table52.AddRow(new string[] {
                            "ScreenSizeInches",
                            "6.8"});
                table52.AddRow(new string[] {
                            "Width",
                            "76"});
                table52.AddRow(new string[] {
                            "Height",
                            "160"});
                table52.AddRow(new string[] {
                            "BatteryType",
                            "Li-Poly"});
                table52.AddRow(new string[] {
                            "BatteryCapacity",
                            "5000"});
                table52.AddRow(new string[] {
                            "Has5G",
                            "true"});
                table52.AddRow(new string[] {
                            "WiFi",
                            "true"});
                table52.AddRow(new string[] {
                            "NFC",
                            "true"});
                table52.AddRow(new string[] {
                            "Bluetooth",
                            "true"});
                table52.AddRow(new string[] {
                            "GPS",
                            "true"});
                table52.AddRow(new string[] {
                            "AGPS",
                            "true"});
                table52.AddRow(new string[] {
                            "Galileo",
                            "true"});
                table52.AddRow(new string[] {
                            "GLONASS",
                            "true"});
                table52.AddRow(new string[] {
                            "QZSS",
                            "true"});
                table52.AddRow(new string[] {
                            "Accelerometer",
                            "true"});
                table52.AddRow(new string[] {
                            "Gyroscope",
                            "true"});
                table52.AddRow(new string[] {
                            "Proximity",
                            "true"});
                table52.AddRow(new string[] {
                            "Compass",
                            "true"});
                table52.AddRow(new string[] {
                            "Barometer",
                            "true"});
                table52.AddRow(new string[] {
                            "Halla",
                            "true"});
                table52.AddRow(new string[] {
                            "AmbientLight",
                            "true"});
                table52.AddRow(new string[] {
                            "Camera",
                            "second camera"});
                table52.AddRow(new string[] {
                            "FingerPrint",
                            "true"});
                table52.AddRow(new string[] {
                            "FaceId",
                            "true"});
                table52.AddRow(new string[] {
                            "PriceAmount",
                            "999.99"});
                table52.AddRow(new string[] {
                            "PriceCurrency",
                            "EUR"});
                table52.AddRow(new string[] {
                            "Description2",
                            "second desc2"});
                table52.AddRow(new string[] {
                            "Description3",
                            "second desc3"});
#line 45
    await testRunner.AndAsync("an existing mobile phone for the by ids request", ((string)(null)), table52, "And ");
#line hidden
                global::Reqnroll.Table table53 = new global::Reqnroll.Table(new string[] {
                            "Id"});
                table53.AddRow(new string[] {
                            "{FirstMobilePhoneId}"});
                table53.AddRow(new string[] {
                            "{SecondMobilePhoneId}"});
#line 86
    await testRunner.WhenAsync("I request the mobile phones by their ids", ((string)(null)), table53, "When ");
#line hidden
                global::Reqnroll.Table table54 = new global::Reqnroll.Table(new string[] {
                            "StatusCode",
                            "Id",
                            "Name",
                            "Brand",
                            "DisplayType",
                            "ScreenSizeInches",
                            "Camera",
                            "PriceAmount",
                            "PriceCurrency"});
                table54.AddRow(new string[] {
                            "200",
                            "{FirstMobilePhoneId}",
                            "First By Ids Phone",
                            "First Brand",
                            "First OLED",
                            "6.4",
                            "first camera",
                            "799.99",
                            "USD"});
                table54.AddRow(new string[] {
                            "200",
                            "{SecondMobilePhoneId}",
                            "Second By Ids Phone",
                            "Second Brand",
                            "Second AMOLED",
                            "6.8",
                            "second camera",
                            "999.99",
                            "EUR"});
#line 90
    await testRunner.ThenAsync("the requested mobile phones are returned successfully", ((string)(null)), table54, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await GetMobilePhonesByIdsFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await GetMobilePhonesByIdsFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
