// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace ProductCatalog.Acceptance.Tests.Features.MobilePhones
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class GetTopMobilePhonesFeature : object, global::Xunit.IClassFixture<GetTopMobilePhonesFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/MobilePhones", "Get top mobile phones", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "GetTopMobilePhones.feature"
#line hidden
        
        public GetTopMobilePhonesFeature(GetTopMobilePhonesFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/MobilePhones/GetTopMobilePhones.feature.ndjson", 5);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Get top mobile phones returns records when mobile phones exist")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Get top mobile phones")]
        [global::Xunit.TraitAttribute("Description", "Get top mobile phones returns records when mobile phones exist")]
        public async global::System.Threading.Tasks.Task GetTopMobilePhonesReturnsRecordsWhenMobilePhonesExist()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Get top mobile phones returns records when mobile phones exist", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 3
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table48 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table48.AddRow(new string[] {
                            "Name",
                            "Top Phone"});
                table48.AddRow(new string[] {
                            "Brand",
                            "Brand"});
                table48.AddRow(new string[] {
                            "Description",
                            "Phone created by top endpoint acceptance test"});
                table48.AddRow(new string[] {
                            "MainPhoto",
                            "main-photo.jpg"});
                table48.AddRow(new string[] {
                            "OtherPhotos",
                            "photo-1.jpg, photo-2.jpg"});
                table48.AddRow(new string[] {
                            "CPU",
                            "Octa-core"});
                table48.AddRow(new string[] {
                            "GPU",
                            "Adreno"});
                table48.AddRow(new string[] {
                            "Ram",
                            "8GB"});
                table48.AddRow(new string[] {
                            "Storage",
                            "256GB"});
                table48.AddRow(new string[] {
                            "DisplayType",
                            "OLED"});
                table48.AddRow(new string[] {
                            "RefreshRateHz",
                            "120"});
                table48.AddRow(new string[] {
                            "ScreenSizeInches",
                            "6.4"});
                table48.AddRow(new string[] {
                            "Width",
                            "72"});
                table48.AddRow(new string[] {
                            "Height",
                            "152"});
                table48.AddRow(new string[] {
                            "BatteryType",
                            "Li-Ion"});
                table48.AddRow(new string[] {
                            "BatteryCapacity",
                            "4500"});
                table48.AddRow(new string[] {
                            "Has5G",
                            "true"});
                table48.AddRow(new string[] {
                            "WiFi",
                            "true"});
                table48.AddRow(new string[] {
                            "NFC",
                            "true"});
                table48.AddRow(new string[] {
                            "Bluetooth",
                            "true"});
                table48.AddRow(new string[] {
                            "GPS",
                            "true"});
                table48.AddRow(new string[] {
                            "AGPS",
                            "true"});
                table48.AddRow(new string[] {
                            "Galileo",
                            "true"});
                table48.AddRow(new string[] {
                            "GLONASS",
                            "true"});
                table48.AddRow(new string[] {
                            "QZSS",
                            "true"});
                table48.AddRow(new string[] {
                            "Accelerometer",
                            "true"});
                table48.AddRow(new string[] {
                            "Gyroscope",
                            "true"});
                table48.AddRow(new string[] {
                            "Proximity",
                            "true"});
                table48.AddRow(new string[] {
                            "Compass",
                            "true"});
                table48.AddRow(new string[] {
                            "Barometer",
                            "true"});
                table48.AddRow(new string[] {
                            "Halla",
                            "false"});
                table48.AddRow(new string[] {
                            "AmbientLight",
                            "true"});
                table48.AddRow(new string[] {
                            "Camera",
                            "camera"});
                table48.AddRow(new string[] {
                            "FingerPrint",
                            "true"});
                table48.AddRow(new string[] {
                            "FaceId",
                            "true"});
                table48.AddRow(new string[] {
                            "PriceAmount",
                            "799.99"});
                table48.AddRow(new string[] {
                            "PriceCurrency",
                            "USD"});
                table48.AddRow(new string[] {
                            "Description2",
                            "desc2"});
                table48.AddRow(new string[] {
                            "Description3",
                            "desc3"});
#line 4
 await testRunner.GivenAsync("an existing set of mobile phones for top list", ((string)(null)), table48, "Given ");
#line hidden
#line 45
 await testRunner.WhenAsync("I request the top mobile phones list", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 46
 await testRunner.ThenAsync("the top mobile phones response is successful and contains records", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Get top mobile phones returns not found when no mobile phones exist")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Get top mobile phones")]
        [global::Xunit.TraitAttribute("Description", "Get top mobile phones returns not found when no mobile phones exist")]
        public async global::System.Threading.Tasks.Task GetTopMobilePhonesReturnsNotFoundWhenNoMobilePhonesExist()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Get top mobile phones returns not found when no mobile phones exist", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 48
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 49
 await testRunner.GivenAsync("mobile phones table is empty for top list", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 50
 await testRunner.WhenAsync("I request the top mobile phones list", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 51
 await testRunner.ThenAsync("the top mobile phones response is not found", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Get top mobile phones returns validation error when amount is incorrect")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Get top mobile phones")]
        [global::Xunit.TraitAttribute("Description", "Get top mobile phones returns validation error when amount is incorrect")]
        public async global::System.Threading.Tasks.Task GetTopMobilePhonesReturnsValidationErrorWhenAmountIsIncorrect()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Get top mobile phones returns validation error when amount is incorrect", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 53
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 54
 await testRunner.WhenAsync("I request the top mobile phones list with amount 0", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table49 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table49.AddRow(new string[] {
                            "StatusCode",
                            "400"});
                table49.AddRow(new string[] {
                            "Title",
                            "Bad Request"});
                table49.AddRow(new string[] {
                            "Detail",
                            "One or more validation errors occurred."});
                table49.AddRow(new string[] {
                            "ErrorMessage",
                            "Amount must be greater than zero."});
                table49.AddRow(new string[] {
                            "ErrorEntity",
                            "Amount"});
                table49.AddRow(new string[] {
                            "ErrorName",
                            "AmountGreaterThanZeroValidationRule"});
#line 55
 await testRunner.ThenAsync("the top mobile phones response fails with validation errors", ((string)(null)), table49, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await GetTopMobilePhonesFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await GetTopMobilePhonesFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
