// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace ProductCatalog.Acceptance.Tests.Features.MobilePhones
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class UpdateMobilePhoneFeature : object, global::Xunit.IClassFixture<UpdateMobilePhoneFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/MobilePhones", "Update mobile phone", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "UpdateMobilePhone.feature"
#line hidden
        
        public UpdateMobilePhoneFeature(UpdateMobilePhoneFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/MobilePhones/UpdateMobilePhone.feature.ndjson", 4);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Update mobile phone returns ok response")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Update mobile phone")]
        [global::Xunit.TraitAttribute("Description", "Update mobile phone returns ok response")]
        public async global::System.Threading.Tasks.Task UpdateMobilePhoneReturnsOkResponse()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Update mobile phone returns ok response", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 3
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table40 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table40.AddRow(new string[] {
                            "Name",
                            "Updated Mobile Phone"});
                table40.AddRow(new string[] {
                            "Brand",
                            "Brand"});
                table40.AddRow(new string[] {
                            "Description",
                            "Updated by acceptance test"});
                table40.AddRow(new string[] {
                            "MainPhoto",
                            "updated-main.jpg"});
                table40.AddRow(new string[] {
                            "OtherPhotos",
                            "updated-photo-1.jpg, updated-photo-2.jpg"});
                table40.AddRow(new string[] {
                            "CPU",
                            "Deca-core"});
                table40.AddRow(new string[] {
                            "GPU",
                            "Mali"});
                table40.AddRow(new string[] {
                            "Ram",
                            "12GB"});
                table40.AddRow(new string[] {
                            "Storage",
                            "512GB"});
                table40.AddRow(new string[] {
                            "DisplayType",
                            "AMOLED"});
                table40.AddRow(new string[] {
                            "RefreshRateHz",
                            "144"});
                table40.AddRow(new string[] {
                            "ScreenSizeInches",
                            "6.8"});
                table40.AddRow(new string[] {
                            "Width",
                            "74"});
                table40.AddRow(new string[] {
                            "Height",
                            "160"});
                table40.AddRow(new string[] {
                            "BatteryType",
                            "Li-Poly"});
                table40.AddRow(new string[] {
                            "BatteryCapacity",
                            "5200"});
                table40.AddRow(new string[] {
                            "Has5G",
                            "false"});
                table40.AddRow(new string[] {
                            "WiFi",
                            "true"});
                table40.AddRow(new string[] {
                            "NFC",
                            "false"});
                table40.AddRow(new string[] {
                            "Bluetooth",
                            "true"});
                table40.AddRow(new string[] {
                            "GPS",
                            "true"});
                table40.AddRow(new string[] {
                            "AGPS",
                            "false"});
                table40.AddRow(new string[] {
                            "Galileo",
                            "true"});
                table40.AddRow(new string[] {
                            "GLONASS",
                            "true"});
                table40.AddRow(new string[] {
                            "QZSS",
                            "false"});
                table40.AddRow(new string[] {
                            "Accelerometer",
                            "true"});
                table40.AddRow(new string[] {
                            "Gyroscope",
                            "false"});
                table40.AddRow(new string[] {
                            "Proximity",
                            "true"});
                table40.AddRow(new string[] {
                            "Compass",
                            "true"});
                table40.AddRow(new string[] {
                            "Barometer",
                            "false"});
                table40.AddRow(new string[] {
                            "Halla",
                            "true"});
                table40.AddRow(new string[] {
                            "AmbientLight",
                            "true"});
                table40.AddRow(new string[] {
                            "Camera",
                            "camera"});
                table40.AddRow(new string[] {
                            "FingerPrint",
                            "false"});
                table40.AddRow(new string[] {
                            "FaceId",
                            "true"});
                table40.AddRow(new string[] {
                            "PriceAmount",
                            "899.99"});
                table40.AddRow(new string[] {
                            "PriceCurrency",
                            "EUR"});
                table40.AddRow(new string[] {
                            "Description2",
                            "desc2"});
                table40.AddRow(new string[] {
                            "Description3",
                            "desc3"});
#line 4
    await testRunner.GivenAsync("an existing mobile phone which will be updated", ((string)(null)), table40, "Given ");
#line hidden
#line 45
    await testRunner.WhenAsync("I submit the update mobile phone request", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table41 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table41.AddRow(new string[] {
                            "StatusCode",
                            "200"});
                table41.AddRow(new string[] {
                            "Name",
                            "Updated Mobile Phone"});
                table41.AddRow(new string[] {
                            "Brand",
                            "Brand"});
                table41.AddRow(new string[] {
                            "PriceAmount",
                            "899.99"});
                table41.AddRow(new string[] {
                            "PriceCurrency",
                            "EUR"});
#line 46
    await testRunner.ThenAsync("the mobile phone is updated successfully", ((string)(null)), table41, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Update mobile phone fails for missing mobile phone")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Update mobile phone")]
        [global::Xunit.TraitAttribute("Description", "Update mobile phone fails for missing mobile phone")]
        public async global::System.Threading.Tasks.Task UpdateMobilePhoneFailsForMissingMobilePhone()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Update mobile phone fails for missing mobile phone", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 54
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table42 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table42.AddRow(new string[] {
                            "Name",
                            "Updated Mobile Phone"});
                table42.AddRow(new string[] {
                            "Brand",
                            "Brand"});
                table42.AddRow(new string[] {
                            "Description",
                            "Updated by acceptance test"});
                table42.AddRow(new string[] {
                            "MainPhoto",
                            "updated-main.jpg"});
                table42.AddRow(new string[] {
                            "OtherPhotos",
                            "updated-photo-1.jpg, updated-photo-2.jpg"});
                table42.AddRow(new string[] {
                            "CPU",
                            "Deca-core"});
                table42.AddRow(new string[] {
                            "GPU",
                            "Mali"});
                table42.AddRow(new string[] {
                            "Ram",
                            "12GB"});
                table42.AddRow(new string[] {
                            "Storage",
                            "512GB"});
                table42.AddRow(new string[] {
                            "DisplayType",
                            "AMOLED"});
                table42.AddRow(new string[] {
                            "RefreshRateHz",
                            "144"});
                table42.AddRow(new string[] {
                            "ScreenSizeInches",
                            "6.8"});
                table42.AddRow(new string[] {
                            "Width",
                            "74"});
                table42.AddRow(new string[] {
                            "Height",
                            "160"});
                table42.AddRow(new string[] {
                            "BatteryType",
                            "Li-Poly"});
                table42.AddRow(new string[] {
                            "BatteryCapacity",
                            "5200"});
                table42.AddRow(new string[] {
                            "Has5G",
                            "false"});
                table42.AddRow(new string[] {
                            "WiFi",
                            "true"});
                table42.AddRow(new string[] {
                            "NFC",
                            "false"});
                table42.AddRow(new string[] {
                            "Bluetooth",
                            "true"});
                table42.AddRow(new string[] {
                            "GPS",
                            "true"});
                table42.AddRow(new string[] {
                            "AGPS",
                            "false"});
                table42.AddRow(new string[] {
                            "Galileo",
                            "true"});
                table42.AddRow(new string[] {
                            "GLONASS",
                            "true"});
                table42.AddRow(new string[] {
                            "QZSS",
                            "false"});
                table42.AddRow(new string[] {
                            "Accelerometer",
                            "true"});
                table42.AddRow(new string[] {
                            "Gyroscope",
                            "false"});
                table42.AddRow(new string[] {
                            "Proximity",
                            "true"});
                table42.AddRow(new string[] {
                            "Compass",
                            "true"});
                table42.AddRow(new string[] {
                            "Barometer",
                            "false"});
                table42.AddRow(new string[] {
                            "Halla",
                            "true"});
                table42.AddRow(new string[] {
                            "AmbientLight",
                            "true"});
                table42.AddRow(new string[] {
                            "Camera",
                            "camera"});
                table42.AddRow(new string[] {
                            "FingerPrint",
                            "false"});
                table42.AddRow(new string[] {
                            "FaceId",
                            "true"});
                table42.AddRow(new string[] {
                            "PriceAmount",
                            "899.99"});
                table42.AddRow(new string[] {
                            "PriceCurrency",
                            "EUR"});
                table42.AddRow(new string[] {
                            "Description2",
                            "desc2"});
                table42.AddRow(new string[] {
                            "Description3",
                            "desc3"});
#line 55
    await testRunner.GivenAsync("mobile phone identify by id not exists", ((string)(null)), table42, "Given ");
#line hidden
#line 96
    await testRunner.WhenAsync("I submit the update mobile phone request for missing mobile phone", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table43 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table43.AddRow(new string[] {
                            "StatusCode",
                            "400"});
                table43.AddRow(new string[] {
                            "Status",
                            "400"});
                table43.AddRow(new string[] {
                            "Title",
                            "Validation failed"});
                table43.AddRow(new string[] {
                            "Detail",
                            "One or more validation errors occurred."});
                table43.AddRow(new string[] {
                            "ErrorMessage",
                            "Mobile phone cannot be null."});
                table43.AddRow(new string[] {
                            "ErrorEntity",
                            "MobilePhone"});
                table43.AddRow(new string[] {
                            "ErrorName",
                            "MobilePhonesIsNullValidationRule"});
#line 97
    await testRunner.ThenAsync("the mobile phone update fails with validation errors", ((string)(null)), table43, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await UpdateMobilePhoneFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await UpdateMobilePhoneFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
