// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductCatalog.Infrastructure.Contexts.Commands;

#nullable disable

namespace ProductCatalog.Infrastructure.Migrations
{
    [DbContext(typeof(ProductsContext))]
    [Migration("20260118043440_AlterMobilePhone4")]
    partial class AlterMobilePhone4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductCatalog.Domain.AggregatesModel.CategoryAggregate.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("TB_Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("587480bb-c126-4f9b-b531-b0244daa4ba4"),
                            ChangedAt = new DateTime(2025, 12, 26, 19, 19, 17, 970, DateTimeKind.Utc).AddTicks(2867),
                            Code = "MOBILE",
                            IsActive = true,
                            Name = "Mobile"
                        },
                        new
                        {
                            Id = new Guid("9656c5c5-8ed9-46e1-a5df-025f5d7885d4"),
                            ChangedAt = new DateTime(2025, 12, 26, 19, 19, 17, 970, DateTimeKind.Utc).AddTicks(2870),
                            Code = "PC",
                            IsActive = true,
                            Name = "Personal Computer"
                        },
                        new
                        {
                            Id = new Guid("f5fd7b52-275e-4710-a578-40a522ac139c"),
                            ChangedAt = new DateTime(2025, 12, 26, 19, 19, 17, 970, DateTimeKind.Utc).AddTicks(2871),
                            Code = "TABLET",
                            IsActive = true,
                            Name = "Tablet"
                        });
                });

            modelBuilder.Entity("ProductCatalog.Domain.AggregatesModel.CategoryAggregate.History.CategoriesHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Operation")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ChangedAt");

                    b.ToTable("TB_Categories_History", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("24daf035-652f-404a-8fd7-785fae68b341"),
                            CategoryId = new Guid("587480bb-c126-4f9b-b531-b0244daa4ba4"),
                            ChangedAt = new DateTime(2025, 12, 26, 19, 19, 17, 970, DateTimeKind.Utc).AddTicks(2867),
                            Code = "MOBILE",
                            IsActive = true,
                            Name = "Mobile",
                            Operation = 0
                        },
                        new
                        {
                            Id = new Guid("b3d060f4-81f4-4d64-b4ac-77b3f39b1e29"),
                            CategoryId = new Guid("9656c5c5-8ed9-46e1-a5df-025f5d7885d4"),
                            ChangedAt = new DateTime(2025, 12, 26, 19, 19, 17, 970, DateTimeKind.Utc).AddTicks(2870),
                            Code = "PC",
                            IsActive = true,
                            Name = "Personal Computer",
                            Operation = 0
                        },
                        new
                        {
                            Id = new Guid("fc500d67-46a9-492a-a861-77fcd73f1bfc"),
                            CategoryId = new Guid("f5fd7b52-275e-4710-a578-40a522ac139c"),
                            ChangedAt = new DateTime(2025, 12, 26, 19, 19, 17, 970, DateTimeKind.Utc).AddTicks(2871),
                            Code = "TABLET",
                            IsActive = true,
                            Name = "Tablet",
                            Operation = 0
                        });
                });

            modelBuilder.Entity("ProductCatalog.Domain.AggregatesModel.CurrencyAggregate.Currency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("TB_Currencies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("1a017544-890c-4219-891f-cd5549473d4e"),
                            ChangedAt = new DateTime(2025, 12, 26, 19, 19, 17, 970, DateTimeKind.Utc).AddTicks(3042),
                            Code = "USD",
                            Description = "US Dollar",
                            IsActive = true
                        },
                        new
                        {
                            Id = new Guid("e73b3ef4-ec2c-4262-81ef-0ac21fbc1ec3"),
                            ChangedAt = new DateTime(2025, 12, 26, 19, 19, 17, 970, DateTimeKind.Utc).AddTicks(3043),
                            Code = "PLN",
                            Description = "Polish Złoty",
                            IsActive = true
                        },
                        new
                        {
                            Id = new Guid("12da255e-6408-4b28-a5b1-84758f889348"),
                            ChangedAt = new DateTime(2025, 12, 26, 19, 19, 17, 970, DateTimeKind.Utc).AddTicks(3044),
                            Code = "EUR",
                            Description = "Euro",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("ProductCatalog.Domain.AggregatesModel.CurrencyAggregate.History.CurrenciesHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Operation")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChangedAt");

                    b.HasIndex("CurrencyId");

                    b.ToTable("TB_Currencies_History", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("1b0d0b8c-2926-415b-a1b8-1843fc189747"),
                            ChangedAt = new DateTime(2025, 12, 26, 19, 19, 17, 970, DateTimeKind.Utc).AddTicks(3042),
                            Code = "USD",
                            CurrencyId = new Guid("1a017544-890c-4219-891f-cd5549473d4e"),
                            Description = "US Dollar",
                            IsActive = true,
                            Operation = 0
                        },
                        new
                        {
                            Id = new Guid("58ad897f-178c-45c9-a8f0-3302a265a9aa"),
                            ChangedAt = new DateTime(2025, 12, 26, 19, 19, 17, 970, DateTimeKind.Utc).AddTicks(3043),
                            Code = "PLN",
                            CurrencyId = new Guid("e73b3ef4-ec2c-4262-81ef-0ac21fbc1ec3"),
                            Description = "Polish Złoty",
                            IsActive = true,
                            Operation = 0
                        },
                        new
                        {
                            Id = new Guid("5bbe9f3d-6299-40b6-a9e6-e851de397563"),
                            ChangedAt = new DateTime(2025, 12, 26, 19, 19, 17, 970, DateTimeKind.Utc).AddTicks(3044),
                            Code = "EUR",
                            CurrencyId = new Guid("12da255e-6408-4b28-a5b1-84758f889348"),
                            Description = "Euro",
                            IsActive = true,
                            Operation = 0
                        });
                });

            modelBuilder.Entity("ProductCatalog.Domain.AggregatesModel.MobilePhoneAggregate.History.MobilePhonesHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AGPS")
                        .HasColumnType("bit");

                    b.Property<bool>("Accelerometer")
                        .HasColumnType("bit");

                    b.Property<bool>("AmbientLight")
                        .HasColumnType("bit");

                    b.Property<bool>("Barometer")
                        .HasColumnType("bit");

                    b.Property<int>("BatteryCapacity")
                        .HasColumnType("int");

                    b.Property<string>("BatteryType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Bluetooth")
                        .HasColumnType("bit");

                    b.Property<string>("CPU")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Camera")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Compass")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DisplayType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("FaceId")
                        .HasColumnType("bit");

                    b.Property<bool>("FingerPrint")
                        .HasColumnType("bit");

                    b.Property<bool>("GLONASS")
                        .HasColumnType("bit");

                    b.Property<bool>("GPS")
                        .HasColumnType("bit");

                    b.Property<string>("GPU")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Galileo")
                        .HasColumnType("bit");

                    b.Property<bool>("Gyroscope")
                        .HasColumnType("bit");

                    b.Property<bool>("Halla")
                        .HasColumnType("bit");

                    b.Property<bool>("Has5G")
                        .HasColumnType("bit");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MainPhoto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("MobilePhoneId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("NFC")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Operation")
                        .HasColumnType("int");

                    b.Property<string>("OtherPhotos")
                        .IsRequired()
                        .HasColumnType("nvarchar(4000)");

                    b.Property<decimal>("PriceAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PriceCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<bool>("Proximity")
                        .HasColumnType("bit");

                    b.Property<bool>("QZSS")
                        .HasColumnType("bit");

                    b.Property<string>("Ram")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("RefreshRateHz")
                        .HasColumnType("int");

                    b.Property<decimal>("ScreenSizeInches")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Storage")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("WiFi")
                        .HasColumnType("bit");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChangedAt");

                    b.HasIndex("MobilePhoneId");

                    b.ToTable("TB_MobilePhones_History", (string)null);
                });

            modelBuilder.Entity("ProductCatalog.Domain.AggregatesModel.MobilePhoneAggregate.MobilePhone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Camera")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("FaceId")
                        .HasColumnType("bit");

                    b.Property<bool>("FingerPrint")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "CommonDescription", "ProductCatalog.Domain.AggregatesModel.MobilePhoneAggregate.MobilePhone.CommonDescription#CommonDescription", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Description");

                            b1.Property<string>("MainPhoto")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("MainPhoto");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Name");

                            b1.PrimitiveCollection<string>("OtherPhotos")
                                .IsRequired()
                                .HasColumnType("nvarchar(4000)")
                                .HasColumnName("OtherPhotos");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Connectivity", "ProductCatalog.Domain.AggregatesModel.MobilePhoneAggregate.MobilePhone.Connectivity#Connectivity", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<bool>("Bluetooth")
                                .HasColumnType("bit")
                                .HasColumnName("Bluetooth");

                            b1.Property<bool>("Has5G")
                                .HasColumnType("bit")
                                .HasColumnName("5G");

                            b1.Property<bool>("NFC")
                                .HasColumnType("bit")
                                .HasColumnName("NFC");

                            b1.Property<bool>("WiFi")
                                .HasColumnType("bit")
                                .HasColumnName("WiFi");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ElectronicDetails", "ProductCatalog.Domain.AggregatesModel.MobilePhoneAggregate.MobilePhone.ElectronicDetails#ElectronicDetails", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("BatteryCapacity")
                                .HasColumnType("int")
                                .HasColumnName("BatteryCapacity");

                            b1.Property<string>("BatteryType")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("BatteryType");

                            b1.Property<string>("CPU")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("CPU");

                            b1.Property<string>("DisplayType")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("DisplayType");

                            b1.Property<string>("GPU")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("GPU");

                            b1.Property<int>("Height")
                                .HasColumnType("int")
                                .HasColumnName("Height");

                            b1.Property<string>("Ram")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Ram");

                            b1.Property<int>("RefreshRateHz")
                                .HasColumnType("int")
                                .HasColumnName("RefreshRateHz");

                            b1.Property<decimal>("ScreenSizeInches")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("ScreenSizeInches");

                            b1.Property<string>("Storage")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Storage");

                            b1.Property<int>("Width")
                                .HasColumnType("int")
                                .HasColumnName("Width");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Price", "ProductCatalog.Domain.AggregatesModel.MobilePhoneAggregate.MobilePhone.Price#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("PriceAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("PriceCurrency");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "SatelliteNavigationSystems", "ProductCatalog.Domain.AggregatesModel.MobilePhoneAggregate.MobilePhone.SatelliteNavigationSystems#SatelliteNavigationSystem", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<bool>("AGPS")
                                .HasColumnType("bit")
                                .HasColumnName("AGPS");

                            b1.Property<bool>("GLONASS")
                                .HasColumnType("bit")
                                .HasColumnName("GLONASS");

                            b1.Property<bool>("GPS")
                                .HasColumnType("bit")
                                .HasColumnName("GPS");

                            b1.Property<bool>("Galileo")
                                .HasColumnType("bit")
                                .HasColumnName("Galileo");

                            b1.Property<bool>("QZSS")
                                .HasColumnType("bit")
                                .HasColumnName("QZSS");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Sensors", "ProductCatalog.Domain.AggregatesModel.MobilePhoneAggregate.MobilePhone.Sensors#Sensors", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<bool>("Accelerometer")
                                .HasColumnType("bit")
                                .HasColumnName("Accelerometer");

                            b1.Property<bool>("AmbientLight")
                                .HasColumnType("bit")
                                .HasColumnName("AmbientLight");

                            b1.Property<bool>("Barometer")
                                .HasColumnType("bit")
                                .HasColumnName("Barometer");

                            b1.Property<bool>("Compass")
                                .HasColumnType("bit")
                                .HasColumnName("Compass");

                            b1.Property<bool>("Gyroscope")
                                .HasColumnType("bit")
                                .HasColumnName("Gyroscope");

                            b1.Property<bool>("Halla")
                                .HasColumnType("bit")
                                .HasColumnName("Halla");

                            b1.Property<bool>("Proximity")
                                .HasColumnType("bit")
                                .HasColumnName("Proximity");
                        });

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("TB_MobilePhones", (string)null);
                });

            modelBuilder.Entity("ProductCatalog.Domain.AggregatesModel.ProductAggregate.History.ProductsHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Operation")
                        .HasColumnType("int");

                    b.Property<decimal>("PriceAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PriceCurrency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ChangedAt");

                    b.HasIndex("ProductId");

                    b.ToTable("TB_Products_History", (string)null);
                });

            modelBuilder.Entity("ProductCatalog.Domain.AggregatesModel.ProductAggregate.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Price", "ProductCatalog.Domain.AggregatesModel.ProductAggregate.Product.Price#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("PriceAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("PriceCurrency");
                        });

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("TB_Products", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
