// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductCatalog.Infrastructure.Contexts.Commands;

#nullable disable

namespace ProductCatalog.Infrastructure.Migrations
{
    [DbContext(typeof(ProductsContext))]
    partial class ProductsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);









            modelBuilder.Entity("ProductCatalog.Domain.AggregatesModel.MobilePhoneAggregate.History.MobilePhonesHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AGPS")
                        .HasColumnType("bit");

                    b.Property<bool>("Accelerometer")
                        .HasColumnType("bit");

                    b.Property<bool>("AmbientLight")
                        .HasColumnType("bit");

                    b.Property<bool>("Barometer")
                        .HasColumnType("bit");

                    b.Property<int>("BatteryCapacity")
                        .HasColumnType("int");

                    b.Property<string>("BatteryType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Bluetooth")
                        .HasColumnType("bit");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Brand");

                    b.Property<string>("CPU")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Camera")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Compass")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description2")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Description3")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("DisplayType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("FaceId")
                        .HasColumnType("bit");

                    b.Property<bool>("FingerPrint")
                        .HasColumnType("bit");

                    b.Property<bool>("GLONASS")
                        .HasColumnType("bit");

                    b.Property<bool>("GPS")
                        .HasColumnType("bit");

                    b.Property<string>("GPU")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Galileo")
                        .HasColumnType("bit");

                    b.Property<bool>("Gyroscope")
                        .HasColumnType("bit");

                    b.Property<bool>("Halla")
                        .HasColumnType("bit");

                    b.Property<bool>("Has5G")
                        .HasColumnType("bit");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MainPhoto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("MobilePhoneId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("NFC")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Operation")
                        .HasColumnType("int");

                    b.Property<string>("OtherPhotos")
                        .IsRequired()
                        .HasColumnType("nvarchar(4000)");

                    b.Property<decimal>("PriceAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PriceCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<bool>("Proximity")
                        .HasColumnType("bit");

                    b.Property<bool>("QZSS")
                        .HasColumnType("bit");

                    b.Property<string>("Ram")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("RefreshRateHz")
                        .HasColumnType("int");

                    b.Property<decimal>("ScreenSizeInches")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Storage")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("WiFi")
                        .HasColumnType("bit");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChangedAt");

                    b.HasIndex("MobilePhoneId");

                    b.ToTable("TB_MobilePhones_History", (string)null);
                });

            modelBuilder.Entity("ProductCatalog.Domain.AggregatesModel.MobilePhoneAggregate.MobilePhone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Camera")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description2")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Description3")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("FaceId")
                        .HasColumnType("bit");

                    b.Property<bool>("FingerPrint")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "CommonDescription", "ProductCatalog.Domain.AggregatesModel.MobilePhoneAggregate.MobilePhone.CommonDescription#CommonDescription", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Brand")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Brand");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Description");

                            b1.Property<string>("MainPhoto")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("MainPhoto");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Name");

                            b1.PrimitiveCollection<string>("OtherPhotos")
                                .IsRequired()
                                .HasColumnType("nvarchar(4000)")
                                .HasColumnName("OtherPhotos");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Connectivity", "ProductCatalog.Domain.AggregatesModel.MobilePhoneAggregate.MobilePhone.Connectivity#Connectivity", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<bool>("Bluetooth")
                                .HasColumnType("bit")
                                .HasColumnName("Bluetooth");

                            b1.Property<bool>("Has5G")
                                .HasColumnType("bit")
                                .HasColumnName("5G");

                            b1.Property<bool>("NFC")
                                .HasColumnType("bit")
                                .HasColumnName("NFC");

                            b1.Property<bool>("WiFi")
                                .HasColumnType("bit")
                                .HasColumnName("WiFi");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ElectronicDetails", "ProductCatalog.Domain.AggregatesModel.MobilePhoneAggregate.MobilePhone.ElectronicDetails#ElectronicDetails", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("BatteryCapacity")
                                .HasColumnType("int")
                                .HasColumnName("BatteryCapacity");

                            b1.Property<string>("BatteryType")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("BatteryType");

                            b1.Property<string>("CPU")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("CPU");

                            b1.Property<string>("DisplayType")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("DisplayType");

                            b1.Property<string>("GPU")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("GPU");

                            b1.Property<int>("Height")
                                .HasColumnType("int")
                                .HasColumnName("Height");

                            b1.Property<string>("Ram")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Ram");

                            b1.Property<int>("RefreshRateHz")
                                .HasColumnType("int")
                                .HasColumnName("RefreshRateHz");

                            b1.Property<decimal>("ScreenSizeInches")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("ScreenSizeInches");

                            b1.Property<string>("Storage")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Storage");

                            b1.Property<int>("Width")
                                .HasColumnType("int")
                                .HasColumnName("Width");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Price", "ProductCatalog.Domain.AggregatesModel.MobilePhoneAggregate.MobilePhone.Price#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("PriceAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("PriceCurrency");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "SatelliteNavigationSystems", "ProductCatalog.Domain.AggregatesModel.MobilePhoneAggregate.MobilePhone.SatelliteNavigationSystems#SatelliteNavigationSystem", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<bool>("AGPS")
                                .HasColumnType("bit")
                                .HasColumnName("AGPS");

                            b1.Property<bool>("GLONASS")
                                .HasColumnType("bit")
                                .HasColumnName("GLONASS");

                            b1.Property<bool>("GPS")
                                .HasColumnType("bit")
                                .HasColumnName("GPS");

                            b1.Property<bool>("Galileo")
                                .HasColumnType("bit")
                                .HasColumnName("Galileo");

                            b1.Property<bool>("QZSS")
                                .HasColumnType("bit")
                                .HasColumnName("QZSS");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Sensors", "ProductCatalog.Domain.AggregatesModel.MobilePhoneAggregate.MobilePhone.Sensors#Sensors", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<bool>("Accelerometer")
                                .HasColumnType("bit")
                                .HasColumnName("Accelerometer");

                            b1.Property<bool>("AmbientLight")
                                .HasColumnType("bit")
                                .HasColumnName("AmbientLight");

                            b1.Property<bool>("Barometer")
                                .HasColumnType("bit")
                                .HasColumnName("Barometer");

                            b1.Property<bool>("Compass")
                                .HasColumnType("bit")
                                .HasColumnName("Compass");

                            b1.Property<bool>("Gyroscope")
                                .HasColumnType("bit")
                                .HasColumnName("Gyroscope");

                            b1.Property<bool>("Halla")
                                .HasColumnType("bit")
                                .HasColumnName("Halla");

                            b1.Property<bool>("Proximity")
                                .HasColumnType("bit")
                                .HasColumnName("Proximity");
                        });

                    b.HasKey("Id");

                    b.ToTable("TB_MobilePhones", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
